# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: bd9539bc-2554-4387-ad75-87dc0e755773
  namespace: bd9539bc-2554-4387-ad75-87dc0e755773
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: true
    instanceType: t3.micro
    disableIngressRules: false
    allowedCIDRBlocks:
      - 127.0.0.1/32
